<?php
namespace ChunkData;

// @@protoc_insertion_point(namespace:.ChunkData.ChunkType)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: chunk.proto
 *
 */
class ChunkType extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.ChunkData.ChunkType)
  
  const ADD = 0;
  const SUB = 1;
  
  // @@protoc_insertion_point(const_scope:.ChunkData.ChunkType)
  
  // @@protoc_insertion_point(class_scope:.ChunkData.ChunkType)
  
  /**
   * @return \ProtocolBuffers\EnumDescriptor
   */
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::ADD,
        "name"  => 'ADD',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::SUB,
        "name"  => 'SUB',
      )));
      // @@protoc_insertion_point(builder_scope:.ChunkData.ChunkType)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
