<?php
namespace ChunkData;

// @@protoc_insertion_point(namespace:.ChunkData.PrefixType)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: chunk.proto
 *
 */
class PrefixType extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.ChunkData.PrefixType)
  
  const PREFIX_4B = 0;
  const FULL_32B = 1;
  
  // @@protoc_insertion_point(const_scope:.ChunkData.PrefixType)
  
  // @@protoc_insertion_point(class_scope:.ChunkData.PrefixType)
  
  /**
   * @return \ProtocolBuffers\EnumDescriptor
   */
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::PREFIX_4B,
        "name"  => 'PREFIX_4B',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::FULL_32B,
        "name"  => 'FULL_32B',
      )));
      // @@protoc_insertion_point(builder_scope:.ChunkData.PrefixType)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
